import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorld,step,reset,DT,TUNE} from '../src/physics.js';
import {lab} from '../src/level.js';
const empty=()=>({id:'test',width:5000,height:1400,spawn:{x:100,y:834},parcel:{x:4500,y:0,w:10,h:10},delivery:{x:4800,y:0,w:20,h:20},solids:[{id:'floor',x:-2000,y:870,w:9000,h:300}],slopes:[],conveyors:[],fans:[],movers:[],hazards:[],stations:[{x:500,y:834}]});
function run(w,n,input={}){for(let i=0;i<n;i++)step(w,input);return w;}
function standing(level=empty()){const w=createWorld(level);run(w,2,{right:true});return w;}
test('timer waits for movement and advances only in fixed ticks',()=>{const w=createWorld(empty());run(w,60);assert.equal(w.time,0);run(w,120,{right:true});assert.equal(w.time,1);});
test('accelerates gradually, reaches running speed, and brakes',()=>{const w=standing();assert.ok(w.p.vx>0&&w.p.vx<100);run(w,60,{right:true});assert.equal(w.p.vx,TUNE.runSpeed);run(w,60);assert.equal(w.p.vx,0);assert.equal(w.status,'running');});
test('air steering preserves above-run-speed boosts',()=>{const w=standing();w.p.vx=800;step(w,{right:true,jumpPressed:true});run(w,10,{right:true});assert.ok(w.p.vx>790);assert.ok(w.p.y<800);});
test('jump release produces a substantially lower apex',()=>{function apex(cut){const w=standing();step(w,{jumpPressed:true});if(cut)step(w,{jumpReleased:true});let top=w.p.y;for(let i=0;i<100;i++){step(w);top=Math.min(top,w.p.y);}return top;}assert.ok(apex(true)-apex(false)>45);});
test('buffered press before landing jumps on contact',()=>{const w=standing();w.p.y=820;w.p.vy=150;w.p.grounded=false;w.p.coyote=0;step(w,{jumpPressed:true});run(w,12);assert.ok(w.p.vy<0);assert.ok(w.p.y<820);});
test('coyote window allows late edge jump but expires',()=>{for(const [delay,allowed] of [[4,true],[15,false]]){const w=standing();w.p.x=10000;run(w,delay,{right:true});step(w,{jumpPressed:true});assert.equal(w.p.vy<0,allowed);}});
test('wall contact supports a kick away and upward',()=>{const l=empty();l.solids.push({id:'wall',x:150,y:500,w:40,h:370});const w=standing(l);w.p.y=700;w.p.x=126;w.p.grounded=false;w.p.coyote=0;run(w,2,{right:true});assert.equal(w.p.wall,1);step(w,{jumpPressed:true,right:true});assert.ok(w.p.vx<0&&w.p.vy<0);assert.equal(w.status,'running');});
test('crouch keeps feet fixed and blocks standing into low ceilings',()=>{const w=standing();step(w,{down:true});assert.equal(w.p.y+w.p.h,870);w.level.solids.push({id:'ceiling',x:90,y:810,w:100,h:32});step(w);assert.equal(w.p.h,22);w.p.x=250;step(w);assert.equal(w.p.h,36);});
test('conveyor accelerates the courier and boost survives takeoff',()=>{const l=empty();l.conveyors.push({id:'belt',x:0,y:856,w:2000,h:14,speed:350});l.spawn.y=820;const w=standing(l);run(w,80,{right:true});assert.ok(w.p.vx>650);step(w,{right:true,jumpPressed:true});assert.ok(w.p.vx>650&&w.p.vy<0);});
test('fan can overcome gravity',()=>{const l=empty();l.fans.push({x:0,y:200,w:1000,h:670,force:3400});const w=standing(l);run(w,30);assert.ok(w.p.y<800);assert.ok(w.p.vy<0);});
test('downhill slope increases speed and stays supported',()=>{const l=empty();l.slopes.push({id:'s',x:100,w:500,y1:600,y2:800});l.spawn={x:100,y:568.8};const w=standing(l);w.p.vx=390;run(w,35,{right:true,down:true});assert.ok(w.p.vx>440);assert.ok(w.p.grounded);assert.equal(w.status,'running');});
test('moving lift carries without overlap and transfers upward velocity',()=>{const l=empty();l.movers.push({id:'lift',kind:'lift',x:90,y:834,w:200,h:20,axis:'y',distance:-260,period:4});l.spawn.y=798;const w=standing(l);run(w,65);assert.equal(w.status,'running');assert.equal(w.p.groundId,'lift');assert.ok(w.p.y<760);step(w,{jumpPressed:true});assert.ok(w.p.vy<-TUNE.jump);assert.equal(w.p.grounded,false);});
test('fast movement cannot tunnel through a thin hazard',()=>{const l=empty();l.hazards.push({x:150,y:700,w:3,h:170});const w=standing(l);w.p.vx=1100;run(w,10,{right:true});assert.equal(w.status,'dead');assert.equal(w.deaths,1);});
test('crushed rider dies rather than remaining inside ceiling',()=>{const l=empty();l.movers.push({id:'lift',kind:'lift',x:90,y:834,w:200,h:20,axis:'y',distance:-260,period:2});l.solids.push({id:'ceiling',x:90,y:650,w:200,h:30});l.spawn.y=798;const w=standing(l);run(w,100);assert.equal(w.status,'dead');});
test('completion requires parcel, freezes clock, and reset clears objectives and machine phase',()=>{const l=empty();l.delivery={x:90,y:800,w:100,h:70};const w=standing(l);assert.notEqual(w.status,'complete');l.parcel={x:90,y:800,w:100,h:70};step(w);assert.equal(w.status,'complete');const t=w.time;run(w,50);assert.equal(w.time,t);reset(w);assert.equal(w.parcel,false);assert.equal(w.time,0);assert.equal(w.started,false);reset(w,0);assert.equal(w.practice,true);});
test('identical inputs after reset produce identical simulation state',()=>{const w=createWorld(lab);function attempt(){for(let i=0;i<150;i++)step(w,{right:true,jumpPressed:i===40,jumpReleased:i===52,down:i>110});return JSON.stringify({p:w.p,time:w.time,machines:w.machines,status:w.status});}const a=attempt();reset(w);assert.equal(attempt(),a);});
test('lab stations start clear and survive settling',()=>{for(let i=0;i<lab.stations.length;i++){const w=createWorld(lab);reset(w,i);run(w,4,{down:true});assert.notEqual(w.status,'dead',`station ${i+1}`);}});
test('early release of a buffered jump still produces a short hop',()=>{const w=createWorld(empty());step(w,{jumpPressed:true,jumpReleased:true});run(w,3);assert.ok(w.p.vy<0&&w.p.vy>-TUNE.jump*.6);});
test('moving lift supports a rider through two complete cycles',()=>{const l=empty();l.movers.push({id:'lift',kind:'lift',x:90,y:834,w:200,h:20,axis:'y',distance:-260,period:4});l.spawn.y=798;const w=standing(l);run(w,960);assert.equal(w.status,'running');assert.equal(w.p.groundId,'lift');assert.ok(Math.abs(w.p.y+w.p.h-w.machines[0].y)<.1);});
